version: "3.9"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: on-failure
    container_name: ${DOCKER_CONTAINER_NAME}
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - gitlab_runner_config

volumes:
  gitlab_runner_config:
    name: gitlab_runner_config

networks:
  gitlab_runner_config:
    name: gitlab_runner_config
